# Site settings
title:          kosop
# description:    ""
url: "kosop1.github.io"

# Author
author:
  name: "kosop"
  email: "kosop@gmail.com"
  url: "kosop1.github.io"

# Build settings
markdown:       kramdown

color: 

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
#social:
  #email: inelaah@gmail.com
  #github: https://github.com/inelaah
  #twitter: https://twitter.com
 #linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
